<div class="content-container home-page-content-wrapper" id="home-page-content">
	<nav class="breadcrumbs-cust" aria-label="breadcrumb breadcrumb-cust">
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="{{CONFIG url}}">{{TR Home}}</a>
			</li>
			<li class="breadcrumb-item">
				{{TR Popular products}}
			</li>
		</ol>
	</nav>



	<!-- <div class="prods-items-container home-page-items gridalicious" style="width: 100%; height: 400px">
            <section class="awe-section-1">
                <div class="container margin-top-15">
                    <div class="row top-sliders">
                        <div class="col-md-8" style="float: left;  position: relative;min-height: 1px;padding-right: 15px;padding-left: 15px">
                            <div id="sync1" class="owl-carousel owl-theme not-dqowl">
                                <div class="item">
                                    <a href="#" class="clearfix" title="Ant Green">
                                        <picture>
                                            <source media="(max-width: 767px)" srcset="https://bizweb.dktcdn.net/thumb/large/100/348/133/themes/709285/assets/slider_1.jpg?1559638811340">
                                            <img data-src="https://bizweb.dktcdn.net/100/348/133/themes/709285/assets/slider_1.jpg?1559638811340" src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" alt="Ant Green" class="img-responsive center-block" />
                                        </picture>
                                    </a>
                                </div>
                                <div class="item">
                                    <a href="#" class="clearfix" title="Ant Organic">
                                        <picture>
                                            <source media="(max-width: 767px)" srcset="https://bizweb.dktcdn.net/thumb/large/100/348/133/themes/709285/assets/slider_2.jpg?1559638811340">
                                            <img data-src="https://bizweb.dktcdn.net/100/348/133/themes/709285/assets/slider_2.jpg?1559638811340" src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" alt="Ant Organic" class="img-responsive center-block" />
                                        </picture>
                                    </a>
                                </div>
                                <div class="item">
                                    <a href="#" class="clearfix" title="Ant Organic">
                                        <picture>
                                            <source media="(max-width: 767px)" srcset="https://bizweb.dktcdn.net/thumb/large/100/348/133/themes/709285/assets/slider_3.jpg?1559638811340">
                                            <img data-src="https://bizweb.dktcdn.net/100/348/133/themes/709285/assets/slider_3.jpg?1559638811340" src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" alt="Ant Organic" class="img-responsive center-block" />
                                        </picture>
                                    </a>
                                </div>
                                <div class="item">
                                    <a href="#" class="clearfix" title="Ant Organic">
                                        <picture>
                                            <source media="(max-width: 767px)" srcset="https://bizweb.dktcdn.net/thumb/large/100/348/133/themes/709285/assets/slider_4.jpg?1559638811340">
                                            <img data-src="https://bizweb.dktcdn.net/100/348/133/themes/709285/assets/slider_4.jpg?1559638811340" src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" alt="Ant Organic" class="img-responsive center-block" />
                                        </picture>
                                    </a>
                                </div>
                                <div class="item">
                                    <a href="#" class="clearfix" title="Ant Organic">
                                        <picture>
                                            <source media="(max-width: 767px)" srcset="https://bizweb.dktcdn.net/thumb/large/100/348/133/themes/709285/assets/slider_5.jpg?1559638811340">
                                            <img data-src="https://bizweb.dktcdn.net/100/348/133/themes/709285/assets/slider_5.jpg?1559638811340" src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" alt="Ant Organic" class="img-responsive center-block" />
                                        </picture>
                                    </a>
                                </div>
                            </div>
                            <div id="sync2" class="owl-carousel owl-theme not-dqowl hidden-xs">
                                <div class="item">IPhone 11 99% "ĐẠI" hạ giá</div>
                                <div class="item">Samsung NOTE 10 giá rẻ tới 20%</div>
                                <div class="item">Ưu đãi 1000 khách hàng đầu tiên</div>
                                <div class="item">Redmi Note 7 CTY Giảm thẳng 2 triệu đồng</div>
                                <div class="item">Đặt trước Mi 9 CTY Giá rẻ hơn 1 triệu</div>
                            </div>
                        </div>
                        <div class="col-md-4 homenews hidden-sm hidden-xs">
                            <figure>
                                <h2><a href="tin-tuc">Tin công nghệ</a></h2>
                            </figure>
                            <ul>
                                <li class="clearfix">
                                    <a href="/oppo-trinh-lang-dien-thoai-gap-nhung-se-khong-san-xuat-hang-loat" title="OPPO tr&#236;nh l&#224;ng điện thoại gập nhưng sẽ kh&#244;ng sản xuất h&#224;ng loạt"></a>
                                    <img width="100" height="70" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC" data-lazyload="https://bizweb.dktcdn.net/thumb/grande/100/348/133/articles/900x450-uploads-2019-02-25-ca681d5a1e.jpg?v=1551952776750" alt="OPPO tr&#236;nh l&#224;ng điện thoại gập nhưng sẽ kh&#244;ng sản xuất h&#224;ng loạt" class="img-responsive center-block" />
                                    <h3>OPPO tr&#236;nh l&#224;ng điện thoại gập nhưng sẽ kh&#244;ng sản xu...</h3>
                                    <span>26/Tháng Hai/2019</span>
                                </li>
                                <li class="clearfix">
                                    <a href="/voi-qualcomm-5g-khong-chi-danh-cho-dien-thoai-ma-con-ca-pc" title="Với Qualcomm, 5G kh&#244;ng chỉ d&#224;nh cho điện thoại m&#224; c&#242;n cả PC"></a>
                                    <img width="100" height="70" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC" data-lazyload="https://bizweb.dktcdn.net/thumb/grande/100/348/133/articles/nen-800x450.jpg?v=1551189624743" alt="Với Qualcomm, 5G kh&#244;ng chỉ d&#224;nh cho điện thoại m&#224; c&#242;n cả PC" class="img-responsive center-block" />
                                    <h3>Với Qualcomm, 5G kh&#244;ng chỉ d&#224;nh cho điện thoại m&#224; c&...</h3>
                                    <span>26/Tháng Hai/2019</span>
                                </li>
                                <li class="clearfix">
                                    <a href="/galalaxy-s10-ra-mat-tai-viet-nam-gia-tot-hon-du-kien-chi-tu-16-trieu" title="Galalaxy S10 ra mắt tại Việt Nam: Gi&#225; tốt hơn dự kiến, chỉ từ 16 triệu"></a>
                                    <img width="100" height="70" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC" data-lazyload="https://bizweb.dktcdn.net/thumb/grande/100/348/133/articles/2-800x450.jpg?v=1551189554080" alt="Galalaxy S10 ra mắt tại Việt Nam: Gi&#225; tốt hơn dự kiến, chỉ từ 16 triệu" class="img-responsive center-block" />
                                    <h3>Galalaxy S10 ra mắt tại Việt Nam: Gi&#225; tốt hơn dự kiến, chỉ từ ...</h3>
                                    <span>26/Tháng Hai/2019</span>
                                </li>
                            </ul>
                            <div class="twobanner">
                                <a href="#" title="Ant Mobile">
                                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC" data-lazyload="https://bizweb.dktcdn.net/100/348/133/themes/709285/assets/banner_under_slider.png?1559638811340" alt="Ant Mobile" class="img-responsive center-block" />
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div> -->


		

	<div class="prods-items-container home-page-items" id="prods-items-container">
		<?php if (not_empty($hs['prods'])): ?>
			<?php foreach ($hs['prods'] as $hs['prod_item']): ?>
				<?php echo hs_loadpage('home/includes/prod_item'); ?>
			<?php endforeach; ?>
		<?php endif; ?>

		<?php if (not_empty($hs['ghosts'])): ?>
			<?php foreach ($hs['ghosts'] as $ghost): ?>
				<?php echo hs_loadpage('home/includes/ghost_item'); ?>
			<?php endforeach; ?>	
		<?php endif; ?>
	</div>

	<div class="prods-grid-items-preloader hidden" id="prods-grid-items-preloader">
		<?php echo hs_loadpage('components/data_preloader'); ?>
	</div>
	<div class="clear"></div>
</div>
 <!-- load phần footer -->
<footer class="footer-fluid">
	<?php echo hs_loadpage('footer/fluid'); ?>	
</footer>
<?php echo hs_loadpage('home/static/js/home_page_script'); ?>	


